# Creating numpy arrays

## Initialize using tuples

In [1]:
from numpy import *
v = array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [2]:
m = array ([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

In [3]:
type(v)
m.shape

(2, 2)

## Using array generating function

In [4]:
x = arange(-1,1,0.1)
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [5]:
x = linspace (0,10,25)
x

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [6]:
x = logspace (0, 10, 10, base=e)
x

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [7]:
x, y = mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [8]:
from numpy import random
m = random.rand(5,5)
m

array([[0.07600524, 0.07147005, 0.88674792, 0.04046142, 0.00651587],
       [0.25977399, 0.12915692, 0.63497803, 0.14129266, 0.74271155],
       [0.54883605, 0.22314818, 0.51291524, 0.37795063, 0.69982814],
       [0.5403369 , 0.56270175, 0.75226349, 0.93582461, 0.82823511],
       [0.82645069, 0.56895311, 0.1142005 , 0.57144389, 0.62771861]])

In [9]:
m = zeros((3,3))
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
m = diag([1,2,3])
m

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## From file I/O

In [11]:
VSURainfall = genfromtxt('VSURainfall.csv')
VSURainfall
VSURainfall.shape

(538,)

In [12]:
m = random.rand(5,5)
savetxt("Random5.csv",m)



## Some array properties

In [13]:
m.ndim

2

In [14]:
m.nbytes

200

# Manipulating Arrays

## Indexing

In [15]:
v[0]

np.int64(1)

In [16]:
m[1,1]
m

array([[0.00223978, 0.81896674, 0.55682207, 0.27015722, 0.69502352],
       [0.34695322, 0.6828258 , 0.27464006, 0.01452228, 0.76518807],
       [0.46195111, 0.70466155, 0.17614588, 0.61012808, 0.9734294 ],
       [0.76197946, 0.2504477 , 0.82575143, 0.95534922, 0.16722774],
       [0.26282084, 0.613527  , 0.89629635, 0.99704265, 0.57651571]])

In [17]:
m[1,:]

array([0.34695322, 0.6828258 , 0.27464006, 0.01452228, 0.76518807])

In [18]:
m[:,1]

array([0.81896674, 0.6828258 , 0.70466155, 0.2504477 , 0.613527  ])

## Fancy Indexing

In [19]:
m

array([[0.00223978, 0.81896674, 0.55682207, 0.27015722, 0.69502352],
       [0.34695322, 0.6828258 , 0.27464006, 0.01452228, 0.76518807],
       [0.46195111, 0.70466155, 0.17614588, 0.61012808, 0.9734294 ],
       [0.76197946, 0.2504477 , 0.82575143, 0.95534922, 0.16722774],
       [0.26282084, 0.613527  , 0.89629635, 0.99704265, 0.57651571]])

In [20]:
v = array([1,2,3,4,5,6])

v1 = v[:4:]
v1

array([1, 2, 3, 4])

In [21]:
m1 = m[1:3,1:4]
m1

array([[0.6828258 , 0.27464006, 0.01452228],
       [0.70466155, 0.17614588, 0.61012808]])

In [22]:
x = arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [23]:
mask = (x>5) * (x<8) 
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True, False, False,
       False, False])

## Function for Extracting Data

In [24]:
indices = where(mask)
indices


(array([11, 12, 13, 14, 15]),)

In [25]:
x[indices]

array([5.5, 6. , 6.5, 7. , 7.5])

In [26]:
diag(m)

array([0.00223978, 0.6828258 , 0.17614588, 0.95534922, 0.57651571])

In [76]:
v2 = arange (-4,4)
v2

array([-4, -3, -2, -1,  0,  1,  2,  3])

In [28]:
row_indices = [1,3,5]

v2.take (row_indices)

array([-3, -1,  1])

In [29]:
which = [1,0,1,0]
choices = [[-2,-2,-2,-2],[4,4,4,4]]
choices

choose (which,choices)

array([ 4, -2,  4, -2])

# Linear algebra Vectorizing

## Scalar-array operations

In [30]:
v1 = arange (0,10)
v1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
v1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
v1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
v1*2, v+3

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]), array([4, 5, 6, 7, 8, 9]))

In [34]:
m * 2

array([[0.00447955, 1.63793348, 1.11364415, 0.54031443, 1.39004705],
       [0.69390643, 1.36565159, 0.54928013, 0.02904457, 1.53037614],
       [0.92390222, 1.40932311, 0.35229177, 1.22025616, 1.9468588 ],
       [1.52395891, 0.50089539, 1.65150286, 1.91069844, 0.33445549],
       [0.52564169, 1.22705401, 1.7925927 , 1.99408531, 1.15303142]])

## Element-wise array-array operations

In [35]:
v1 * v1
v1.shape
v.shape

(6,)

In [36]:
m * m

array([[5.01660081e-06, 6.70706520e-01, 3.10050822e-01, 7.29849217e-02,
        4.83057697e-01],
       [1.20376534e-01, 4.66251069e-01, 7.54271647e-02, 2.10896712e-04,
        5.85512785e-01],
       [2.13398828e-01, 4.96547904e-01, 3.10273720e-02, 3.72256274e-01,
        9.47564795e-01],
       [5.80612691e-01, 6.27240484e-02, 6.81865425e-01, 9.12692130e-01,
        2.79651179e-02],
       [6.90747957e-02, 3.76415384e-01, 8.03347144e-01, 9.94094053e-01,
        3.32370365e-01]])

In [37]:
m.shape

(5, 5)

In [83]:
v3 = arange (0,5)
v3.shape
v3

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [39]:
m* v3

array([[0.        , 0.81896674, 1.11364415, 0.81047165, 2.78009409],
       [0.        , 0.6828258 , 0.54928013, 0.04356685, 3.06075229],
       [0.        , 0.70466155, 0.35229177, 1.83038424, 3.8937176 ],
       [0.        , 0.2504477 , 1.65150286, 2.86604766, 0.66891097],
       [0.        , 0.613527  , 1.7925927 , 2.99112796, 2.30606284]])

## Matrix algebra

In [40]:
dot (m,v3)

array([5.52317663, 4.33642506, 6.78105515, 5.43690918, 7.7033105 ])

In [41]:
dot (m,m)

array([[0.92989365, 1.44749298, 1.1702799 , 1.30329372, 1.61611702],
       [0.57672904, 1.41702312, 1.12692632, 1.04801272, 1.47454499],
       [1.04763264, 1.73363731, 1.85807559, 1.79594029, 1.69495877],
       [1.2419645 , 1.71878701, 1.57728927, 1.79273078, 1.78121427],
       [1.53874528, 1.86917416, 1.81276078, 2.154103  , 2.02371499]])

## Matrix Computation

In [42]:
linalg.inv(m)

array([[ 0.43101208,  0.22402855,  0.37460563,  1.64668952, -1.92711453],
       [ 9.11562399, -6.60628294,  2.68184165,  4.09284645, -7.93654897],
       [-3.45604544,  3.92013229, -2.71244534, -1.50289006,  3.97923824],
       [ 1.49969873, -2.84122056,  1.62628514,  0.63711756, -0.96766714],
       [-7.11790336,  5.74740875, -1.62035002, -3.8716285 ,  6.54622522]])

In [43]:
linalg.det(m)

np.float64(0.03342862135523944)

In [44]:
mean(m[:,3])

np.float64(0.5694398903603396)

In [45]:
std(v1)

np.float64(2.8722813232690143)

In [46]:
min(v1)

np.int64(0)

In [47]:
max(v1)

np.int64(9)

In [48]:
sum(v1)

np.int64(45)

In [49]:
prod(v1)

np.int64(0)

In [50]:
cumsum(v1)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## Reshaping, resizing and stacking arrays

In [51]:
m

array([[0.00223978, 0.81896674, 0.55682207, 0.27015722, 0.69502352],
       [0.34695322, 0.6828258 , 0.27464006, 0.01452228, 0.76518807],
       [0.46195111, 0.70466155, 0.17614588, 0.61012808, 0.9734294 ],
       [0.76197946, 0.2504477 , 0.82575143, 0.95534922, 0.16722774],
       [0.26282084, 0.613527  , 0.89629635, 0.99704265, 0.57651571]])

In [52]:
i, j = m.shape
print (i,j)

5 5


In [53]:
v3 = m.flatten()
v3
v3.shape

(25,)

In [54]:
v3= v3[:, newaxis]

In [55]:
v3.shape

(25, 1)

In [56]:
a = array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [57]:
repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [58]:
tile(a,3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [59]:
b = array([[5, 6]])
b

array([[5, 6]])

In [60]:
concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [62]:
vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## Copy and "deep copy"

In [64]:
A = array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [65]:
B = A

In [66]:
B[0,0] = 8
B

array([[8, 2],
       [3, 4]])

In [67]:
A

array([[8, 2],
       [3, 4]])

In [68]:
B = copy(A)
B

array([[8, 2],
       [3, 4]])

In [69]:
B [0,0] = 10
B

array([[10,  2],
       [ 3,  4]])

In [70]:
A

array([[8, 2],
       [3, 4]])

## Iterating over array elements

In [71]:
v = array([1,2,3,4])

for i in v:
    print(i)

1
2
3
4


In [72]:
M = array([[1,2], [3,4]])

for i in M:
    for j in i:
        print(j)

1
2
3
4


In [73]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

no element in M is larger than 5


In [79]:
if (M > 5).all():
    print("all element in M is larger than 5")